LogTime yes
LogSyslog false
Foreground true
TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /run/clamav/clamd.ctl
User clamav
DatabaseDirectory /var/lib/clamav
StreamMaxLength 256M
MaxFileSize 256M
MaxScanSize 256M
SelfCheck 3600
